export const SEND_CONTACT_FORM           = 'SEND_CONTACT_FORM';
export const SEND_CONTACT_FORM_FAILURE   = 'SEND_CONTACT_FORM_FAILURE';
export const REMOVE_CONTACT_FORM         = 'REMOVE_CONTACT_FORM';
export const REMOVE_CONTACT_FORM_FAILURE = 'REMOVE_CONTACT_FORM_FAILURE';
