export const FETCH_GLUONS           = 'FETCH_GLUONS';
export const FETCH_GLUONS_FAILURE   = 'FETCH_GLUONS_FAILURE';

export const ADD_GLUON              = 'ADD_GLUON';
export const ADD_GLUON_FAILURE      = 'ADD_GLUON_FAILURE';

export const REMOVE_ADDED_GLUON     = 'REMOVE_ADDED_GLUON';

export const FETCH_EDITING_GLUON    = 'FETCH_EDITING_GLUON';
export const FETCH_EDITING_GLUON_FAILURE = 'FETCH_EDITING_GLUON_FAILURE';

export const EDIT_GLUON             = 'EDIT_GLUON';
export const EDIT_GLUON_FAILURE     = 'EDIT_GLUON_FAILURE';

export const DELETE_GLUON           = 'DELETE_GLUON';
export const DELETE_GLUON_FAILURE   = 'DELETE_GLUON_FAILURE';

export const REMOVE_DELETED_GLUON   = 'REMOVE_DELETED_GLUON';

