export const FETCH_GLUONS   = 'FETCH_GLUONS';
export const FETCH_GLUONS_FAILURE   = 'FETCH_GLUONS_FAILURE';

export const DELETE_GLUON           = 'DELETE_GLUON';
export const DELETE_GLUON_FAILURE   = 'DELETE_GLUON_FAILURE';

