export const FETCH_GLUONS   = 'FETCH_GLUONS';
export const FETCH_GLUONS_FAILURE   = 'FETCH_GLUONS_FAILURE';

export const FETCH_SUB_GLUONS   = 'FETCH_SUB_GLUONS';
export const FETCH_SUB_GLUONS_FAILURE   = 'FETCH_SUB_GLUONS_FAILURE';
