export const FETCH_ONE_QUARK         = 'FETCH_ONE_QUARK';
export const FETCH_ONE_QUARK_FAILURE = 'FETCH_ONE_QUARK_FAILURE';
export const FETCH_ONE_QUARK_NOT_FOUND = 'FETCH_ONE_QUARK_NOT_FOUND';

export const CHANGE_CURRENT_QUARK    = 'CHANGE_CURRENT_QUARK';

export const FETCH_QUARKS            = 'FETCH_QUARKS';
export const FETCH_QUARKS_FAILURE    = 'FETCH_QUARKS_FAILURE';

export const FETCH_PICKUPS           = 'FETCH_PICKUPS';
export const FETCH_PICKUPS_FAILURE   = 'FETCH_PICKUPS_FAILURE';

export const SEARCH_QUARKS           = 'SEARCH_QUARKS';
export const SEARCH_QUARKS_FAILURE   = 'SEARCH_QUARKS_FAILURE';

export const CHANGE_SEARCH_KEYWORD   = 'CHANGE_SEARCH_KEYWORD';
export const CHANGE_SEARCH_KEYWORD_FAILURE   = 'CHANGE_SEARCH_KEYWORD_FAILURE';

export const ADD_QUARK               = 'ADD_QUARK';
export const ADD_QUARK_FAILURE       = 'ADD_QUARK_FAILURE';

export const REMOVE_ADDED_QUARK      = 'REMOVE_ADDED_QUARK';

export const FETCH_EDITING_QUARK     = 'FETCH_EDITING_QUARK';
export const FETCH_EDITING_QUARK_FAILURE = 'FETCH_EDITING_QUARK_FAILURE';

export const READ_EDITING_QUARK      = 'READ_EDITING_QUARK';
export const READ_EDITING_QUARK_FAILURE = 'READ_EDITING_QUARK_FAILURE';

export const EDIT_QUARK              = 'EDIT_QUARK';
export const EDIT_QUARK_FAILURE      = 'EDIT_QUARK_FAILURE';

export const REMOVE_EDITED_QUARK     = 'REMOVE_EDITED_QUARK';

export const DELETE_QUARK            = 'DELETE_QUARK';
export const DELETE_QUARK_FAILURE    = 'DELETE_QUARK_FAILURE';

export const REMOVE_DELETED_QUARK    = 'REMOVE_DELETED_QUARK';
