export const FETCH_QUARK   = 'FETCH_QUARK';
export const FETCH_QUARK_FAILURE   = 'FETCH_QUARK_FAILURE';
export const FETCH_QUARK_PROPERTIES   = 'FETCH_QUARK_PROPERTIES';
export const FETCH_QUARK_PROPERTIES_FAILURE   = 'FETCH_QUARK_PROPERTIES_FAILURE';
