export const FETCH_QUARK   = 'FETCH_QUARK';
export const FETCH_QUARK_FAILURE   = 'FETCH_QUARK_FAILURE';

export const FETCH_QUARK_PROPERTIES   = 'FETCH_QUARK_PROPERTIES';
export const FETCH_QUARK_PROPERTIES_FAILURE   = 'FETCH_QUARK_PROPERTIES_FAILURE';

export const CHANGE_SEARCH_KEYWORD   = 'CHANGE_SEARCH_KEYWORD';
export const CHANGE_SEARCH_KEYWORD_FAILURE   = 'CHANGE_SEARCH_KEYWORD_FAILURE';

export const DELETE_QUARK           = 'DELETE_QUARK';
export const DELETE_QUARK_FAILURE   = 'DELETE_QUARK_FAILURE';


export const FETCH_ONE_QUARK   = 'FETCH_ONE_QUARK';
export const FETCH_ONE_QUARK_FAILURE   = 'FETCH_ONE_QUARK_FAILURE';
